version: '3.8'

services:
   mongodb:
     image: mongo
     container_name: mongodb
     ports:
      - "27017:27017"

   app:
     build: .
     container_name: bugtracker-container
     ports:
      - "3000:3000"
     depends_on:
      - mongodb
volumes:
   mongo_data:
